sudo: required
language: ruby
rvm:
  - 2.5.1
addons:
  chrome: stable
before_install:
  - gem install bundler -v 1.16.1
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
